# filepath: /Users/manolozocco/.pyenv/versions/3.11.9/lib/python3.11/site-packages/audiobookdl/altro_modulo.py
# ...existing code...
from audiobookdl.log_helper import some_function
# ...existing code...
